### ISSUE TITLE
Lbryum Plan

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbryum#230]
This is the epic plan for merging lbryum into lbry repo. It is based on feedback collected in #226.

- [ ] replace the networking stack with twisted (getting rid of the threading and raw socket handling)
- [ ] can be used without activating the networking stack
- [ ] `restore` command needs more tests (8ed6088)
- [ ] remove `getclaimtrie` from lbryum client and server
- [ ] rename API functions to follow the noun_verb API naming scheme that's been established in lbrynet
- [ ] resolve or transfer any remaining valid issues to lbry repository
- [ ] actually merge the codebases
- [ ] update README to indicate that the code has been merged into lbry
- [ ] archive this repo

**Comment by lyoshenka** [comment]
let me know if you want help with naming api methods. im pretty good at that

**Comment by kauffj** [comment]
@eukreign I wasn't suggesting incorporating alternative wallet implementations be part of this ticket, just that we consider the future expectation of doing so.

For example, rather than just creating the wallet class (or classes), create an interface that all wallet implementations must satisfy.
